FROM openjdk:11-jre-slim as jdkbase
FROM jdkbase

RUN apt update && apt install -y iputils-ping \
    && apt install -y nano && apt install -y curl \
    && apt install -y zip && apt install -y unzip \
    && apt install -y traceroute && apt install -y telnet

ADD target/chargepoints-0.0.1-SNAPSHOT.jar /run/cpa.jar
ADD target/classes/application.properties /appconfig/application.properties

ENTRYPOINT ["java","-jar","run/cpa.jar","-Xms128m","-Xmx4096m", "--spring.config.location=file:///appconfig/application.properties"]
