version: "3.8"
services:
  cpa:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: cpa
    container_name: cpa
    networks:
      - net
    ports:
      - 8081:8081

networks:
  net:
    name: net
    driver: bridge